version: "3"
services:
  web:
    image: pineag/pltk:master
    ports:
      - '8000:80'
    environment:
      - DATA_SERVER_HOST=data:3000
      - FILE_SERVER_HOST=file:8000
    depends_on:
      - data
      - file
    command: [sh, /docker/start.sh]
  data:
    image: pineag/boltbase:master
    volumes:
      - "./tmp/data:/data"
  file:
    image: pineag/blitzfile:master
    volumes:
      - "./tmp/files:/files"