# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Electron Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Yarn Install
      run: yarn install
    - name: Build Dependencies
      run: |
          cd maintenance
          npx gulp buildLibs
          npx gulp buildApps
    - name: Build Electron
      run: |
          cd projects/desktop
          yarn build
          cd build
          zip PineLiveToolkit-win32-x64.zip PineLiveToolkit-win32-x64
          cp PineLiveToolkit-win32-x64.zip /PineLiveToolkit-win32-x64.zip
