# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Electron Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        node-version: 18.x
        include:
          - os: windows-latest
            electron_platform: win32
            electron_arch: x64
          - os: macos-latest
            electron_platform: darwin
            electron_arch: x86_64
          - os: macos-latest
            electron_platform: darwin
            electron_arch: arm64
          - os: ubuntu-latest
            electron_platform: linux
            electron_arch: x86_64
          - os: ubuntu-latest
            electron_platform: linux
            electron_arch: arm64

        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Yarn Install
      run: |
        yarn install
    - name: Build Dependencies
      run: |
          cd maintenance
          npx gulp buildLibs
    - name: Build Frontend
      run: |
          cd projects/frontend
          yarn build
    - name: Build Electron
      run: |
          cd projects/desktop
          yarn build
          npx gulp buildProduction --platform=${{ matrix.electron_platform }} --arch=${{ matrix.electron_arch }}
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: projects/desktop/build/PineLiveToolkit-${{ matrix.electron_platform }}-${{ matrix.electron_arch }}.zip
        asset_name: PineLiveToolkit-${{ matrix.electron_platform }}-${{ matrix.electron_arch }}.zip
        tag: ${{ github.ref }}
        overwrite: true
        body: "Uploaded from Github Actions"
